begin;
create extension if not exists pgtap with schema extensions;
select plan(19);
insert into auth.users(id) values('9c000000-0000-4000-8000-000000000001');
insert into public.staff_profiles(user_id,full_name,role) values('9c000000-0000-4000-8000-000000000001','Synthetic RTO Admin','ADMIN');
select set_config('request.jwt.claim.sub','9c000000-0000-4000-8000-000000000001',true);
select set_config('request.jwt.claim.role','authenticated',true);
insert into public.customers(id,full_name,licence_number,licence_expiry,status) values('4c000000-0000-4000-8000-000000000001','Synthetic RTO Customer','SYN-RTO-001',current_date+365,'ACTIVE');
insert into public.vehicles(id,registration,make,model,year,odometer,operational_status,weekly_rate) values('5c000000-0000-4000-8000-000000000001','RTO001','Synthetic','RTO',2024,1000,'AVAILABLE',100);
insert into public.vehicle_assignments(id,customer_id,vehicle_id,assigned_at,pickup_odometer,assignment_status,created_by) values('7c000000-0000-4000-8000-000000000001','4c000000-0000-4000-8000-000000000001','5c000000-0000-4000-8000-000000000001',now(),1000,'ACTIVE','9c000000-0000-4000-8000-000000000001');
select public.create_agreement('4c000000-0000-4000-8000-000000000001','5c000000-0000-4000-8000-000000000001','RENT_TO_OWN',current_date,current_date+7,current_date,100,0,200,2,null,null);
select public.transition_agreement((select id from public.agreements),'PENDING_SIGNATURE');select public.transition_agreement((select id from public.agreements),'ACTIVE');
select is((select payments_completed::int from public.rent_to_own_completion_readiness),0,'RTO progress begins unpaid');
select isnt((select ready_to_complete from public.rent_to_own_completion_readiness),true,'RTO is not initially ready');
select throws_ok($$select public.confirm_rto_ownership_transfer((select id from public.agreements),'EXT-UAT-1','Synthetic legal confirmation')$$,'contractual payment schedule is not complete','cannot confirm before payment completion');
select public.record_manual_payment((select id from public.agreements),200,now(),'SYN-RTO-PAID','Synthetic full contract payment');
select is((select payments_completed::int from public.rent_to_own_completion_readiness),2,'stored schedule reports completed payments');
select is((select amount_paid from public.rent_to_own_completion_readiness),200.00::numeric,'stored allocations report amount paid');
select is((select remaining_contractual_balance from public.rent_to_own_completion_readiness),0.00::numeric,'stored terms report zero remaining balance');
select throws_ok($$select public.transition_agreement((select id from public.agreements),'COMPLETED')$$,'rent-to-own completion requires paid schedule and confirmed external ownership transfer','completion cannot imply legal transfer');
select lives_ok($$select public.confirm_rto_ownership_transfer((select id from public.agreements),'EXT-UAT-1','Synthetic legal confirmation')$$,'admin can record external confirmation');
select ok((select ready_to_complete from public.rent_to_own_completion_readiness),'paid and externally confirmed RTO is ready');
select throws_ok($$delete from public.rto_ownership_transfer_confirmations$$,'42501','ownership transfer confirmation history is immutable','confirmation cannot be deleted');
select lives_ok($$select public.transition_agreement((select id from public.agreements),'COMPLETED')$$,'confirmed RTO can complete');
select is((select status from public.agreements),'COMPLETED','agreement reaches completed state');
select is((select count(*)::int from public.rto_ownership_transfer_confirmations),1,'exactly one confirmation retained');
select ok((select public.daily_operations_snapshot() ? 'vehicles_ready'),'daily operations exposes reviewed task counts');
select ok((select public.management_report_snapshot() ? 'finance'),'management report exposes trustworthy finance totals');
select is((select count(*)::int from public.scheduled_jobs where job_key='EXPIRE_INVITATIONS'),1,'invitation expiry is a reviewed scheduled job');
select lives_ok($$select public.update_business_payment_instructions('Use the synthetic UAT reference only',true,'Synthetic approval')$$,'admin can approve payment instructions');
select ok((select customer_display_approved from public.business_payment_settings),'approved instructions become customer-visible');
select throws_ok($$delete from public.business_payment_setting_history$$,'operational execution history is immutable','payment setting history is immutable');
select * from finish();rollback;
