#!/bin/bash

echo "🚀 GitHub Deployment Setup"
echo "=========================================="
echo ""
echo "This guide will help you deploy to GitHub Pages"
echo ""
echo "📋 STEP 1: Create a GitHub Repository"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://github.com/new"
echo "2. Repository name: business-online"
echo "3. Description: Starr365 Car Rental + Veera Food Corner"
echo "4. Choose: Public"
echo "5. Click: Create repository"
echo ""
echo "📋 STEP 2: Copy Your Repository URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Look for this format:"
echo "  https://github.com/yourusername/business-online.git"
echo ""
echo "📋 STEP 3: Push Code to GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands one by one:"
echo ""
echo "  cd ~/Desktop/deploy-online"
echo ""
echo "  git remote add origin https://github.com/yourusername/business-online.git"
echo ""
echo "  git branch -M main"
echo ""
echo "  git push -u origin main"
echo ""
echo "⚠️  Note: You may need to enter your GitHub credentials"
echo ""
echo "📋 STEP 4: Enable GitHub Pages"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://github.com/yourusername/business-online"
echo "2. Click: Settings (top right)"
echo "3. Left sidebar: Pages"
echo "4. Source: Deploy from branch"
echo "5. Branch: main"
echo "6. Folder: / (root)"
echo "7. Click: Save"
echo ""
echo "✅ Wait 1-2 minutes..."
echo ""
echo "🎉 Your site is now LIVE at:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  🏠 https://yourusername.github.io/business-online/"
echo "  🚗 https://yourusername.github.io/business-online/rentals"
echo "  🍽️  https://yourusername.github.io/business-online/food"
echo ""
echo "═════════════════════════════════════════════════════════"
echo ""
echo "💡 Future Updates:"
echo ""
echo "  After making changes, push to GitHub:"
echo "    git add ."
echo "    git commit -m 'Your message'"
echo "    git push"
echo ""
echo "  Your site updates automatically!"
echo ""
echo "❓ Troubleshooting:"
echo ""
echo "  If you get 'authentication failed':"
echo "    1. Generate a token: github.com/settings/tokens"
echo "    2. Use token as password when prompted"
echo ""
echo "  If pages don't show up after 5 minutes:"
echo "    1. Refresh the GitHub Pages settings"
echo "    2. Check the 'Actions' tab for build errors"
echo ""
echo "═════════════════════════════════════════════════════════"
