#!/bin/bash

# 🚀 GITHUB QUICK DEPLOY
# Copy-paste these commands to deploy immediately

echo "═══════════════════════════════════════════════════════════"
echo "🚀 GitHub Deployment - Quick Start"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Follow these 3 simple steps:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Create Repository at https://github.com/new"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • Repository name: business-online"
echo "  • Public: YES"
echo "  • Create repository"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Push Code (Run these commands)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd ~/Desktop/deploy-online"
echo "git remote add origin https://github.com/Nischit-stha/business-online.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Enable GitHub Pages"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Go to your repo on GitHub"
echo "  2. Settings → Pages"
echo "  3. Branch: main, Folder: /"
echo "  4. Save & Wait 2 minutes"
echo ""
echo "🎉 LIVE URLS:"
echo "═══════════════════════════════════════════════════════════"
echo "https://nischit-stha.github.io/business-online/"
echo "https://nischit-stha.github.io/business-online/rentals"
echo "https://nischit-stha.github.io/business-online/food"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ Your code is READY in: ~/Desktop/deploy-online/"
echo "✅ Git history saved: 2 commits"
echo "✅ All files organized and configured"
echo ""
