import { decideDocument, uploadDocument, viewDocument } from '@/lib/document-actions';

type Version = { id:string; document_type:string; original_filename:string; status:string; expiry_date:string|null; uploaded_at:string; uploaded_by:string; verified_at:string|null; rejection_reason:string|null; file_size:number };
export function DocumentWorkflow({ subjectId, returnPath, types, versions }: { subjectId:string; returnPath:string; types:string[]; versions:Version[] }) {
  return <section><h2>Private documents</h2><p>PDF, JPEG or PNG only, up to 10 MiB. Viewing uses a 60-second private link.</p>
    {types.map(type => { const history=versions.filter(v=>v.document_type===type); const current=history.find(v=>v.status!=='SUPERSEDED'); return <div className="card" key={type}><h3>{type.replaceAll('_',' ')}</h3><p>Current: <strong>{current?.status ?? 'MISSING'}</strong>{current?.expiry_date ? ` · expires ${current.expiry_date}` : ''}</p>
      <form action={uploadDocument} className="inline-form" encType="multipart/form-data"><input type="hidden" name="subjectId" value={subjectId}/><input type="hidden" name="documentType" value={type}/><input type="hidden" name="returnPath" value={returnPath}/><label>Document<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required/></label><label>Expiry<input name="expiryDate" type="date" required={type!=='PROOF_OF_ADDRESS'}/></label><button>Upload replacement</button></form>
      {current && <><form action={viewDocument} className="inline-form"><input type="hidden" name="documentId" value={current.id}/><input type="hidden" name="returnPath" value={returnPath}/><button>View securely</button></form>{current.status==='SUBMITTED' && <form action={decideDocument} className="inline-form"><input type="hidden" name="documentId" value={current.id}/><input type="hidden" name="returnPath" value={returnPath}/><label>Decision<select name="decision"><option>VERIFIED</option><option>REJECTED</option></select></label><label>Expiry<input name="expiryDate" type="date" defaultValue={current.expiry_date ?? ''}/></label><label>Rejection reason<input name="reason" maxLength={500}/></label><button>Save decision</button></form>}</>}
      <details><summary>Version history ({history.length})</summary><div className="table-wrap"><table><thead><tr><th>Uploaded</th><th>File</th><th>Size</th><th>Status</th><th>Expiry</th><th>Verified</th></tr></thead><tbody>{history.map(v=><tr key={v.id}><td>{new Date(v.uploaded_at).toLocaleString('en-AU')}</td><td>{v.original_filename}</td><td>{Math.ceil(v.file_size/1024)} KiB</td><td>{v.status}{v.rejection_reason?` · ${v.rejection_reason}`:''}</td><td>{v.expiry_date??'—'}</td><td>{v.verified_at?new Date(v.verified_at).toLocaleString('en-AU'):'—'}</td></tr>)}</tbody></table></div></details>
    </div>})}</section>;
}
