import {StaffNav} from '@/components/staff-nav';
import {requireStaff} from '@/lib/auth';
import {cancelNotification,generateNotifications,manuallyQueueNotification,markNotificationDelivered,processNotifications,retryNotification,updateNotificationSettings} from '@/lib/notification-actions';

const groups=[['Needs Attention',['FAILED','SUPPRESSED']],['Scheduled',['SCHEDULED']],['Queued',['QUEUED','SENDING']],['Sent',['SENT']],['Delivered',['DELIVERED']],['Failed',['FAILED']],['Suppressed',['SUPPRESSED']]] as const;
export default async function NotificationsPage({searchParams}:{searchParams:Promise<{error?:string;q?:string;type?:string;page?:string}>}){
 const params=await searchParams;const {supabase}=await requireStaff();const page=Math.max(1,Number(params.page)||1),limit=75,from=(page-1)*limit;
 let query=supabase.from('notifications').select('id,type,channel,subject,rendered_message,scheduled_for,sent_at,status,retry_count,max_retries,created_at,provider_message_id,customers(full_name)').order('created_at',{ascending:false}).range(from,from+limit-1);if(params.type)query=query.eq('type',params.type);
 const [{data},{data:attention},{data:customers},{data:vehicles},{data:settings}]=await Promise.all([query,supabase.from('notification_attention').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('customers').select('id,full_name').eq('status','ACTIVE').order('full_name'),supabase.from('vehicles').select('id,registration').order('registration'),supabase.from('notification_settings').select('*').single()]);
 const filtered=params.q?data?.filter(n=>n.customers?.[0]?.full_name?.toLowerCase().includes(params.q!.toLowerCase())||n.type.includes(params.q!.toUpperCase())):data;
 return <main><StaffNav/><p className="eyebrow">Provider-neutral · safe local delivery only</p><h1>Notification operations</h1>{params.error&&<p className="error">{params.error}</p>}
 <form className="inline-form"><input name="q" defaultValue={params.q} placeholder="Search customer or type"/><select name="type" defaultValue={params.type??''}><option value="">All types</option>{['PAYMENT_DUE','PAYMENT_OVERDUE','PAYMENT_RECEIVED','SERVICE_DUE','SERVICE_OVERDUE','LICENCE_EXPIRING','LICENCE_EXPIRED','PICKUP_REMINDER','RETURN_REMINDER','ISSUE_STATUS_UPDATE'].map(x=><option key={x}>{x}</option>)}</select><button>Filter</button></form>
 <div className="inline-form"><form action={generateNotifications}><button>Generate due reminders</button></form><form action={processNotifications}><button>Run local worker</button></form></div>
 <section><h2>Settings</h2><form action={updateNotificationSettings} className="form-grid"><label>Days before payment due<input name="preDueDays" defaultValue={settings?.payment_pre_due_days?.join(',')}/></label><label>Due/overdue stages<input name="paymentStages" defaultValue={settings?.payment_stages?.join(',')}/></label><label>Pickup hours<input name="pickupHours" defaultValue={settings?.pickup_hours?.join(',')}/></label><label>Return hours<input name="returnHours" defaultValue={settings?.return_hours?.join(',')}/></label><label>Licence days<input name="licenceStages" defaultValue={settings?.licence_stages?.join(',')}/></label><label>Maximum retries<input name="maxRetries" type="number" min="1" max="5" defaultValue={settings?.max_retries}/></label><label><input name="issueAutoNotify" type="checkbox" defaultChecked={settings?.issue_status_auto_notify}/> Automatically notify safe issue status changes</label><button>Save bounded settings</button></form></section>
 <section><h2>Manually queue supported reminder</h2><form action={manuallyQueueNotification} className="inline-form"><select name="customerId" required><option value="">Customer</option>{customers?.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select><select name="vehicleId"><option value="">No vehicle</option>{vehicles?.map(v=><option key={v.id} value={v.id}>{v.registration}</option>)}</select><select name="type">{['PAYMENT_DUE','PAYMENT_OVERDUE','SERVICE_DUE','SERVICE_OVERDUE','LICENCE_EXPIRING','LICENCE_EXPIRED','PICKUP_REMINDER','RETURN_REMINDER'].map(x=><option key={x}>{x}</option>)}</select><button>Queue</button></form></section>
 {groups.map(([label,statuses])=>{const rows=label==='Needs Attention'?attention:filtered?.filter(n=>(statuses as readonly string[]).includes(n.status));return <section key={label}><h2>{label}</h2><div className="table-wrap"><table><thead><tr><th>Scheduled</th><th>Customer</th><th>Type</th><th>Channel</th><th>Status</th><th>Attempts</th><th>Inspect</th><th>Action</th></tr></thead><tbody>{rows?.map(n=><tr key={`${label}-${n.id}`}><td>{new Date(n.scheduled_for??n.created_at).toLocaleString('en-AU')}</td><td>{n.customers?.[0]?.full_name??n.customer_name??'—'}</td><td>{n.type}</td><td>{n.channel}</td><td>{n.status}</td><td>{n.retry_count}/{n.max_retries}</td><td>{n.rendered_message?<details><summary>Message</summary>{n.subject&&<strong>{n.subject}<br/></strong>}<span>{n.rendered_message}</span></details>:n.attention_reason}</td><td>{n.status==='FAILED'?<form action={retryNotification}><input type="hidden" name="id" value={n.id}/><button>Retry</button></form>:['QUEUED','SCHEDULED'].includes(n.status)?<form action={cancelNotification}><input type="hidden" name="id" value={n.id}/><button>Cancel</button></form>:n.status==='SENT'?<form action={markNotificationDelivered}><input type="hidden" name="id" value={n.id}/><input type="hidden" name="providerMessageId" value={n.provider_message_id}/><button>Record local receipt</button></form>:'—'}</td></tr>)}</tbody></table></div></section>})}
 <p><a href={`/notifications?page=${Math.max(1,page-1)}`}>Previous</a> · <a href={`/notifications?page=${page+1}`}>Next</a></p></main>;
}
