import { StaffNav } from '@/components/staff-nav';
import { requireStaff } from '@/lib/auth';
import { cancelNotification, generateNotifications, manuallyQueueNotification, processNotifications, retryNotification } from '@/lib/notification-actions';

const groups=[['Queued',['QUEUED']],['Scheduled',['SCHEDULED']],['Sent',['SENT','DELIVERED']],['Failed',['FAILED']],['Cancelled',['CANCELLED','SUPPRESSED']]] as const;
export default async function NotificationsPage({searchParams}:{searchParams:Promise<{error?:string}>}){
 const {error}=await searchParams; const {supabase}=await requireStaff(); const [{data},{data:customers},{data:vehicles}]=await Promise.all([supabase.from('notifications').select('id,type,channel,subject,rendered_message,scheduled_for,sent_at,status,retry_count,max_retries,created_at,customers(full_name)').order('created_at',{ascending:false}).limit(300),supabase.from('customers').select('id,full_name').eq('status','ACTIVE').order('full_name'),supabase.from('vehicles').select('id,registration').order('registration')]);
 return <main><StaffNav/><p className="eyebrow">Provider-neutral · safe local delivery only</p><h1>Notification operations</h1>{error&&<p className="error">{error}</p>}<div className="inline-form"><form action={generateNotifications}><button>Generate due reminders</button></form><form action={processNotifications}><button>Run local worker</button></form></div>
 <section><h2>Manually queue supported reminder</h2><form action={manuallyQueueNotification} className="inline-form"><select name="customerId" required><option value="">Customer</option>{customers?.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select><select name="vehicleId"><option value="">No vehicle</option>{vehicles?.map(v=><option key={v.id} value={v.id}>{v.registration}</option>)}</select><select name="type">{['PAYMENT_DUE','PAYMENT_OVERDUE','SERVICE_DUE','SERVICE_OVERDUE','LICENCE_EXPIRING','LICENCE_EXPIRED','PICKUP_REMINDER','RETURN_REMINDER'].map(x=><option key={x}>{x}</option>)}</select><button>Queue</button></form></section>
 {groups.map(([label,statuses])=><section key={label}><h2>{label}</h2><div className="table-wrap"><table><thead><tr><th>Scheduled</th><th>Customer</th><th>Type</th><th>Channel</th><th>Status</th><th>Attempts</th><th>Inspect</th><th>Action</th></tr></thead><tbody>{data?.filter(n=>(statuses as readonly string[]).includes(n.status)).map(n=><tr key={n.id}><td>{new Date(n.scheduled_for).toLocaleString('en-AU')}</td><td>{n.customers?.[0]?.full_name??'—'}</td><td>{n.type}</td><td>{n.channel}</td><td>{n.status}</td><td>{n.retry_count}/{n.max_retries}</td><td><details><summary>Message</summary>{n.subject&&<strong>{n.subject}<br/></strong>}<span>{n.rendered_message}</span></details></td><td>{n.status==='FAILED'?<form action={retryNotification}><input type="hidden" name="id" value={n.id}/><button>Retry</button></form>:['QUEUED','SCHEDULED'].includes(n.status)?<form action={cancelNotification}><input type="hidden" name="id" value={n.id}/><button>Cancel</button></form>:'—'}</td></tr>)}</tbody></table></div></section>)}</main>;
}
