import { expect,test,type Page } from '@playwright/test';
const staff={email:'e2e.staff@example.test',password:'Synthetic-Staff-2026!'};
const customerA={email:'e2e.customer.a@example.test',password:'Synthetic-Customer-A-2026!'};
async function login(page:Page,kind:'staff'|'customer'){const account=kind==='staff'?staff:customerA;await page.goto(kind==='staff'?'/login':'/portal/login');await page.getByLabel('Email').fill(account.email);await page.getByLabel('Password').fill(account.password);await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(kind==='staff'?/\/fleet$/:/\/portal$/);}
test.describe('staff trial workflows',()=>{test.beforeEach(async({page})=>login(page,'staff'));
 for(const [name,path,heading] of [
  ['dashboard','/owner',/Operations|Dashboard|Good/],['today','/today',/Today/],['reports','/reports',/Reports/],['customer lookup','/customers',/Customers/],['vehicle lookup','/fleet',/Fleet/],['payment review','/payments',/Payments/],['issue creation','/operations/issues/new',/Report vehicle issue/],['maintenance action','/operations/maintenance',/Maintenance/],['portal request review','/operations/portal-requests',/Customer requests/],['toll fine review','/operations/tolls-fines',/Toll|fine/i],
 ] as const)test(name,async({page})=>{await page.goto(path);await expect(page).toHaveURL(new RegExp(path.replaceAll('/','\\/')));await expect(page.getByRole('heading',{level:1})).toContainText(heading);});
 test('staff cannot use customer-only context',async({page})=>{await page.goto('/portal');await expect(page).toHaveURL(/portal\/access-denied/);});
 test('today exposes prioritised operational actions',async({page})=>{await page.goto('/today');await expect(page.getByRole('heading',{name:'Today'})).toBeVisible();await expect(page.getByRole('link',{name:/Review payment|Open checklist|Open return|Handle issue|Review service|Review compliance|Review readiness|Respond|Review delivery/}).first()).toBeVisible();});
 test('durable notifications are the only communication navigation',async({page})=>{await page.goto('/notifications');await expect(page.getByRole('link',{name:'Notifications'})).toHaveAttribute('aria-current','page');await expect(page.getByRole('link',{name:'Messaging'})).toHaveCount(0);await page.goto('/messaging');await expect(page.getByRole('heading',{name:'Messaging has moved'})).toBeVisible();await expect(page.getByRole('link',{name:'Open Notification operations'})).toBeVisible();});
});
test.describe('customer trial workflows',()=>{test.beforeEach(async({page})=>login(page,'customer'));
 for(const [name,path,heading] of [['dashboard','/portal',/Avery|Portal/],['payments','/portal/payments',/Payments/],['vehicle','/portal/my-car',/My car/],['document upload','/portal/documents',/Documents/],['issue submission','/portal/issues',/Vehicle issues/],['portal request','/portal/profile',/Profile and requests/]] as const)test(name,async({page})=>{await page.goto(path);await expect(page.getByRole('heading',{level:1})).toContainText(heading);});
 test('logout',async({page})=>{await page.getByRole('button',{name:/sign out/i}).click();await expect(page).toHaveURL(/portal\/login/);});
 test('customer cannot access staff routes',async({page})=>{await page.goto('/fleet');await expect(page).toHaveURL(/access-denied/);});
 test('customer A cannot access customer B data through projections',async({request})=>{const response=await request.post(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/auth/v1/token?grant_type=password`,{headers:{apikey:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!},data:customerA});const token=(await response.json()).access_token;const rows=await request.get(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/portal_profile?customer_id=eq.10000000-0000-4000-8000-000000000002`,{headers:{apikey:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,Authorization:`Bearer ${token}`}});expect(await rows.json()).toEqual([]);});
});

test('major staff pages remain usable at representative widths',async({page})=>{test.setTimeout(90_000);await login(page,'staff');for(const [width,height,path] of [[1440,900,'/owner'],[1280,800,'/fleet'],[768,1024,'/customers'],[390,844,'/payments']] as const){await page.setViewportSize({width,height});await page.goto(path);await expect(page.getByRole('heading',{level:1})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.keyboard.press('Tab');await expect(page.locator(':focus')).toBeVisible();}});
test('customer portal remains usable at tablet and common mobile widths',async({page})=>{await login(page,'customer');for(const [width,height,path] of [[768,1024,'/portal'],[430,932,'/portal/payments'],[390,844,'/portal/my-car'],[360,800,'/portal/profile']] as const){await page.setViewportSize({width,height});await page.goto(path);await expect(page.getByRole('heading',{level:1})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}});
test('password recovery entry point is labelled without account disclosure',async({page})=>{await page.goto('/forgot-password');await expect(page.getByRole('heading',{level:1})).toBeVisible();await expect(page.getByLabel('Email')).toBeVisible();});

test('priority staff pages expose landmarks, headings, labelled controls, and keyboard focus',async({page})=>{test.setTimeout(120_000);await login(page,'staff');for(const path of ['/today','/owner','/fleet','/customers','/payments','/operations/maintenance','/operations/issues']){await page.goto(path);await expect(page.locator('main')).toHaveCount(1);await expect(page.getByRole('heading',{level:1})).toBeVisible();await page.keyboard.press('Tab');await expect(page.locator(':focus')).toBeVisible();const unnamed=await page.locator('button:not([aria-label]):not([aria-labelledby])').evaluateAll(nodes=>nodes.filter(node=>!(node.textContent??'').trim()).length);expect(unnamed).toBe(0);}});
test('auth and portal priority pages remain labelled at mobile width',async({page})=>{await page.setViewportSize({width:360,height:800});for(const path of ['/login','/forgot-password','/portal/login']){await page.goto(path);await expect(page.locator('main')).toHaveCount(1);await expect(page.getByRole('heading',{level:1})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}await login(page,'customer');for(const path of ['/portal','/portal/payments','/portal/my-car','/portal/documents','/portal/issues','/portal/profile']){await page.goto(path);await expect(page.getByRole('heading',{level:1})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}});

test('changed staff workflows remain practical at required widths',async({page})=>{test.setTimeout(120_000);await login(page,'staff');for(const width of [1440,768,430,390,360]){await page.setViewportSize({width,height:900});for(const path of ['/today','/operations/pickups','/operations/returns','/operations/compliance','/notifications']){await page.goto(path);await expect(page.getByRole('heading',{level:1})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}}});

test('portal revoke succeeds, explains loss of access, and can be restored',async({browser})=>{const staffContext=await browser.newContext(),customerContext=await browser.newContext();const staffPage=await staffContext.newPage(),customerPage=await customerContext.newPage();await login(staffPage,'staff');await login(customerPage,'customer');await staffPage.goto('/admin/accounts');const row=staffPage.locator('form.inline-actions').filter({hasText:'Avery Example'});await row.getByRole('button',{name:'Deactivate and revoke sessions'}).click();await expect(staffPage.locator('p[role="status"]')).toContainText('revoked');await customerPage.reload();await expect(customerPage).toHaveURL(/portal\/(access-denied|login)/);if(await customerPage.getByRole('heading',{name:'Portal access unavailable'}).isVisible())await expect(customerPage.getByText(/Contact Veera Rentals/)).toBeVisible();const disabled=staffPage.locator('form.inline-actions').filter({hasText:'Avery Example'});await disabled.getByRole('button',{name:'Activate'}).click();await expect(staffPage.locator('p[role="status"]')).toContainText('enabled');await staffContext.close();await customerContext.close();});
