import { requireAdmin } from '@/lib/auth';
import { inviteAccount,resendInvitation,setAccountEnabled } from '@/lib/account-actions';
import { StaffNav } from '@/components/staff-nav';
export default async function AccountsPage({searchParams}:{searchParams:Promise<{error?:string;invited?:string;resent?:string;updated?:string;type?:string}>}){
 const {supabase}=await requireAdmin();const [{data:customers},{data:invites},{data:staff},{data:portals},params]=await Promise.all([
  supabase.from('customers').select('id,full_name').eq('status','ACTIVE').order('full_name'),supabase.from('account_invitations').select('*').order('created_at',{ascending:false}).limit(100),
  supabase.from('staff_profiles').select('user_id,full_name,role,status,is_active').order('full_name'),supabase.from('customer_portal_accounts').select('user_id,customer_id,status').order('created_at',{ascending:false}),searchParams]);
 return <><StaffNav/><main className="page-shell"><h1>Account access</h1><p>Administrator-only provisioning. Account links are retained for audit and can be safely restored.</p>{params.error&&<p className="error" role="alert"><strong>Access was not changed.</strong> {params.error}</p>}{(params.invited||params.resent)&&<p className="success" role="status">Invitation updated successfully.</p>}{params.updated&&<p className="success" role="status">{params.type==='customer'?'Customer portal':'Staff'} access was {params.updated==='revoked'?'revoked and active sessions blocked':'enabled'} successfully.</p>}
 <section><h2>Invite account</h2><form action={inviteAccount} className="form-card"><label>Account type<select name="accountType"><option value="STAFF">Staff</option><option value="CUSTOMER">Customer</option></select></label><label>Name<input name="fullName" maxLength={120} required/></label><label>Email<input name="email" type="email" required/></label><label>Staff role<select name="staffRole"><option value="STAFF">Staff</option><option value="ADMIN">Administrator</option></select></label><label>Customer (customer accounts only)<select name="customerId"><option value="">Not a customer account</option>{customers?.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label><button>Send 24-hour invitation</button></form></section>
 <section><h2>Invitations</h2><div className="table-wrap"><table><thead><tr><th>Email</th><th>Type</th><th>Status</th><th>Expires</th><th>Action</th></tr></thead><tbody>{invites?.map(i=><tr key={i.id}><td>{i.email}</td><td>{i.account_type}</td><td>{i.status}</td><td>{new Date(i.expires_at).toLocaleString('en-AU')}</td><td>{['PENDING','EXPIRED'].includes(i.status)&&<form action={resendInvitation}><input type="hidden" name="invitationId" value={i.id}/><input type="hidden" name="email" value={i.email}/><button>Resend</button></form>}</td></tr>)}</tbody></table></div></section>
 <section><h2>Staff access</h2>{staff?.map(s=><form key={s.user_id} action={setAccountEnabled} className="inline-actions"><span>{s.full_name} · {s.role} · {s.status}</span><input type="hidden" name="userId" value={s.user_id}/><input type="hidden" name="accountType" value="STAFF"/><input type="hidden" name="fullName" value={s.full_name}/><input type="hidden" name="staffRole" value={s.role}/><input type="hidden" name="enabled" value={s.is_active?'false':'true'}/><button>{s.is_active?'Disable and revoke sessions':'Enable'}</button></form>)}</section>
 <section><h2>Customer portal access</h2>{portals?.map(p=><form key={p.user_id} action={setAccountEnabled} className="inline-actions"><span>{customers?.find(c=>c.id===p.customer_id)?.full_name??p.customer_id} · {p.status}</span><input type="hidden" name="userId" value={p.user_id}/><input type="hidden" name="customerId" value={p.customer_id}/><input type="hidden" name="accountType" value="CUSTOMER"/><input type="hidden" name="enabled" value={p.status==='ACTIVE'?'false':'true'}/><button>{p.status==='ACTIVE'?'Deactivate and revoke sessions':'Activate'}</button></form>)}</section></main></>;
}
